name: windows-wrapper-llvm-msvc-build
  
concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
  
permissions:
  contents: write
  
on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      BUILD_TYPE: Release
    steps:

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.1'

    - name: Setup llvm-msvc
      uses: backengineering/setup-llvm-msvc@v5
      with:
        version: llvm-msvc-v777.1.7
    
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
          path: llvm-msvc
          submodules: 'recursive'
          
    - name: Build llvm
      run: |
        cmake -Bbuild -TLLVM-MSVC_v143 `
        -DLLVM_INCLUDE_TESTS=OFF `
        -DLLVM_INCLUDE_EXAMPLES=OFF `
        -DLLDB_ENABLE_PYTHON=OFF `
        -DLLVM_ENABLE_LIBXML2=OFF `
        -DLLVM_ENABLE_ZLIB=OFF `
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
        -DLLVM_USE_CRT_RELEASE=MT `
        -DCMAKE_INSTALL_PREFIX=install `
        -DLLVM_TARGETS_TO_BUILD="X86;AArch64" `
        -DLLVM_ENABLE_PROJECTS="clang;lld" `
        llvm-msvc\\llvm
        cmake --build build --config ${{ env.BUILD_TYPE }}
        cmake --build build --config ${{ env.BUILD_TYPE }} --target install
        
    - name: Package llvm
      run: |
        7z a -v1500m windows-wrapper-llvm-msvc.zip install
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-wrapper-llvm-msvc
        path: windows-wrapper-llvm-msvc.zip.00*
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: windows-wrapper-llvm-msvc.zip.00*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
